Update Openwrt-AutoBuild.yml

diff --git a/.github/workflows/Openwrt-AutoBuild.yml b/.github/workflows/Openwrt-AutoBuild.yml
--- a/.github/workflows/Openwrt-AutoBuild.yml
+++ b/.github/workflows/Openwrt-AutoBuild.yml
@@ -193,7 +193,7 @@ jobs:
         run: |
           mkdir -p firmware
           if [ "$LOG" = "true" ]; then
-            find OpenWrt/ \( -type f -name "*_full.log" -o -name "*_error.log"\) -exec cp {} ./firmware/ \; 2>/dev/null || true
+            find OpenWrt/ -maxdepth 1 \( -type f -name "*_full.log" -o -name "*_error.log" \) -exec cp -f {} ./firmware/ \; 2>/dev/null || true
             ls firmware
           else
             find OpenWrt/bin/targets/ \( -type d -name "packages" -o -name "*buildinfo" -o -name "*json" -o -name "*txt" -o -name "*manifest" \) -exec rm -rf {} + 2>/dev/null  
@@ -204,7 +204,7 @@ jobs:
             for file in *; do tar -czf "$file.tar.gz" "$file" && [ -f "$file" ] && rm -f "$file"; done
             tar -xzf sha256sums.tar.gz && tar -xzf release.tar.gz && tar -xzf ${{matrix.target}}.config.tar.gz && rm -f {sha256sums.tar.gz,release.tar.gz,${{matrix.target}}.config.tar.gz}  
             mv sha256sums ${{ matrix.target }}_sha256sums
-            [ "$REPO_NAME" = "lede" ] && rename 's/openwrt/$REPO_NAME/' openwrt-*
+            [ "$REPO_NAME" = "lede" ] && rename "s/openwrt/$REPO_NAME/" openwrt-*
             echo "FIRMWARE_STATUS=true" >> $GITHUB_ENV
             compgen -G "*efi*" > /dev/null && echo "EFI=true" >> $GITHUB_ENV
             compgen -G "*squashfs*" > /dev/null && echo "COMBINED=true" >> $GITHUB_ENV
